apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: aws-load-balancer-controller
  namespace: kube-system
spec:
  interval: 24h
  url: https://aws.github.io/eks-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: aws-load-balancer-controller
  namespace: kube-system
spec:
  interval: 1m
  chart:
    spec:
      chart: aws-load-balancer-controller
      version: "1.11.0" # APP VERSION : v2.11.0
      sourceRef:
        kind: HelmRepository
        name: aws-load-balancer-controller
        namespace: kube-system
      interval: 12h
  values:
    installCRDs: true
    clusterName: my-cluster
